LAB/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace TaskManagaer.Models
{
    public class AppDbContext : DbContext
    {
        public DbSet<LAB.Models.Task> Tasks { get; set; }
        public string DbPath { get; set; }
        public AppDbContext()
        {
            var folder = Environment.SpecialFolder.LocalApplicationData;
            var path = Environment.GetFolderPath(folder);
            DbPath = System.IO.Path.Join(path, "tasks.db");
        }
        protected override void OnConfiguring(DbContextOptionsBuilder
       options)
        => options.UseSqlite($"Data Source={DbPath}");
      
    }
   

}

LAB/Models/ErrorViewModel.cs
namespace LAB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LAB/Models/Task.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace LAB.Models
{
    public class Task
    {
        [HiddenInput]
        public int Id { get; set; }
        [Required(ErrorMessage = "Podaj Autora")]
        public string Author { get; set; }
        [RegularExpression(".+\\@.+\\.[a-z]{2,3}")]
        [Required(ErrorMessage = "Podaj poprawny Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Podaj nazwe zadania")]
        public string TaskName { get; set; }
        [MinLength(length: 5,ErrorMessage ="Opis musi mieć conajmniej 5 znaków")]
        public string Description { get; set; }


    }

}

LAB/Controllers/HomeController.cs
using LAB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LAB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LAB/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using TaskManagaer.Models;
using System.Data;

namespace LAB.Controllers
{
    public class TaskController : Controller
    {


        private static AppDbContext context = new AppDbContext();

        public IActionResult Index()
        { 
            // Return the list of data from the database
            var data = context.Tasks.ToList();

            return View(data);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var data = context.Tasks.Where(x => x.Id == id).FirstOrDefault();
            if (data != null)
            {
                context.Tasks.Remove(data);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View("Index");

        }
        [HttpGet]

        public ActionResult Edit(int Id)
        {

            var data = context.Tasks.Where(x => x.Id == Id).FirstOrDefault();
            return View(data);

        }

        // To specify that this will be
        // invoked when post method is called
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int Id, Models.Task model)
        {


            // Use of lambda expression to access
            // particular record from a database
            var data = context.Tasks.Where(x => x.Id == Id).FirstOrDefault();

            // Checking if any such record exist
            if (data != null)
            {
                data.Author = data.Author;
                data.Email = data.Email;

                data.TaskName = model.TaskName;
                data.Description = model.Description;

                context.SaveChanges();

                // It will redirect to
                // the Read method
                return RedirectToAction("Index");
            }
            else
                return View();

        }


        public IActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Form(LAB.Models.Task task)
        {
            if (ModelState.IsValid)
            {
                context.Tasks.Add(task);
                context.SaveChanges();
                // return View("Index", context.Tasks.ToList());
                return RedirectToAction("Index");

            }
            else
                return View();
        }
    }
}

LAB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="logo-center">
        <img src="assets/iconmonstr-dashboard-lined-240.png" alt="alternatetext">
    </div>
    <h1>Welcome to Task manager</h1>
    <h2>JW</h2>
    <a class="btn btn-outline-info" asp-controller="Task" asp-action="Index">Get started!</a>
</div>

LAB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LAB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Task" asp-action="Index">Task Manager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Task" asp-action="Form">Add Task</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LAB/Views/Task/Edit.cshtml
@model LAB.Models.Task
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Edit task</h1>
<form asp-action="Edit" method="post">
    <div asp-validation-summary="All"></div>
    <div>
        <label asp-for="TaskName">Task name</label>
        <div class="form-group">
            <span asp-validation-for="TaskName" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="TaskName" />
    </div>
    <div>
        <label asp-for="Description">Task description</label>
        <div class="form-group">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="Description" />
    </div>
    <button class="btn btn-outline-primary button" type="submit" value="Submit">Submit</button>



</form>

LAB/Views/Task/Form.cshtml
@model LAB.Models.Task
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Add task</h1>
 <div class="form">
<form asp-action="Form" method="post">
    <div asp-validation-summary="All"></div>
    <div>
        <label asp-for="Author">Your name</label>
        <div class="form-group">
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="Author" />
    </div>
    <div>
        <label asp-for="Email">Email</label>
        <div class="form-group">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="Email" />
    </div>
    <div>
        <label asp-for="TaskName">Task name</label>
        <div class="form-group">
            <span asp-validation-for="TaskName" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="TaskName" />
    </div>
    <div>
        <label asp-for="Description">Task description</label>
        <div class="form-group">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <input class="form-control" type="text" asp-for="Description" />
    </div>
    <button class="btn btn-outline-primary button" type="submit" value="Submit">Submit</button>

</form>
</div>

LAB/Views/Task/Index.cshtml
@model List<LAB.Models.Task>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Task manager</h1>
<table class="table center">

    <thead class="thead-dark">
        <tr>
            <th class="bg bg-dark text-white" scope="col">#</th>
            <th class="bg bg-dark text-white" scope="col">Author</th>
            <th class="bg bg-dark text-white" scope="col">Email</th>
            <th class="bg bg-dark text-white" scope="col">Task Name</th>
            <th class="bg bg-dark text-white" scope="col">Description</th>
            <th class="bg bg-dark text-white" scope="col">Edit</th>
            <th class="bg bg-dark text-white" scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td> @task.Id</td>
                <td>@task.Author</td>
                <td> @task.Email</td>
                <td>@task.TaskName</td>
                <td>@task.Description</td>
                <td>
                    <a class="btn btn-outline-primary" asp-controller="Task" asp-action="Edit"
                   asp-route-id=@task.Id>Edit</a>
                </td>
                <td>
                    <a class="btn btn-outline-danger" asp-controller="Task" asp-action="Delete"
                   asp-route-id=@task.Id>Delete</a>
                </td>
            </tr>

        }
    </tbody>

</table>
<a class="btn btn-outline-primary button" asp-controller="Task" asp-action="Form">Add</a>